import { List } from 'immutable';
import { createDataFn } from '../../utils';

const currentProjectInitial = {
  isLoading: false,
  address: '',
  approvalAfterGuarantorsSign: false,
  approvalAfterPurchasersSign: false,
  approvalAfterVendorsSign: false,
  bills: null,
  clientId: null,
  completionDate: '',
  correspondenceCcEmails: List(),
  dateCreated: '',
  footerTemplateId: null,
  fullAddress: '',
  headerTemplateId: null,
  id: null,
  isDeleted: false,
  isLocked: false,
  isSequentialLotNumber: false,
  isUploadingTemplate: false,
  lotNumberEnd: 0,
  lotNumberPrefix: null,
  lotNumberStart: 0,
  lotStatuses: List(),
  masterAdjustments: List(),
  masterContractHash: null,
  masterContractState: 0,
  matter: '',
  modifiedDate: '',
  name: '',
  newLotNumbers: null,
  notes: List(),
  parties: null,
  partyId: null,
  projectSigns: null,
  signContractError: null,
  signContractLabel: 'Not Signed',
  signContractMessage: null,
  signContractOrderId: null,
  signContractStatus: 0,
  signItCcEmails: List(),
  state: 0,
  templateIsDirty: false,
  totalNumOfLot: 0,
  vendorAgents: List(),
  vendorSolicitorAddressLine1: '',
  vendorSolicitorAddressLine2: '',
  vendorSolicitorContact: '',
  vendorSolicitorCorrespondenceCcEmails: List(),
  vendorSolicitorEmail: '',
  vendorSolicitorFax: '',
  vendorSolicitorFullAddress: '',
  vendorSolicitorName: '',
  vendorSolicitorPhone: '',
  vendorSolicitorPostcode: '',
  vendorSolicitorReference: '',
  vendorSolicitorSignItCcEmails: List(),
  vendorSolicitorState: 0,
  vendorSolicitorSuburb: '',
  vendors: List(),
  willLock: false
};

export const getCurrentProjectInstance = createDataFn(currentProjectInitial);
